// Nombres Darija Rabat
// On retire les anciennes cartes "Cent" et "Mille" pour garder un ordre numérique propre.
for (let i = DATA.length - 1; i >= 0; i--) {
  if (DATA[i].cat === 'Nombres' && (DATA[i].fr === 'Cent' || DATA[i].fr === 'Mille')) DATA.splice(i, 1);
}

const NUMBER_DATA = [
  ['0','sifr','صفر'],
  ['1','wa7ed','واحد'],
  ['2','jouj','جوج'],
  ['3','tlata','ثلاثة'],
  ['4','rb3a','ربعة'],
  ['5','khmsa','خمسة'],
  ['6','setta','ستة'],
  ['7','seb3a','سبعة'],
  ['8','tmnya','تمانية'],
  ['9','tes3oud','تسعود'],
  ['10','3chra','عشرة'],
  ['11','7dach','حداش'],
  ['12','tnach','طناش'],
  ['13','teltach','تلتاش'],
  ['14','rb3tach','ربعتاش'],
  ['15','khmstach','خمستاش'],
  ['16','settach','ستاش'],
  ['17','seb3tach','سبعتاش'],
  ['18','tmntach','تمنطاش'],
  ['19','tes3tach','تسعتاش'],
  ['20','3chrin','عشرين'],
  ['21','wa7ed w 3chrin','واحد وعشرين'],
  ['22','jouj w 3chrin','جوج وعشرين'],
  ['23','tlata w 3chrin','ثلاثة وعشرين'],
  ['24','rb3a w 3chrin','ربعة وعشرين'],
  ['25','khmsa w 3chrin','خمسة وعشرين'],
  ['26','setta w 3chrin','ستة وعشرين'],
  ['27','seb3a w 3chrin','سبعة وعشرين'],
  ['28','tmnya w 3chrin','تمانية وعشرين'],
  ['29','tes3oud w 3chrin','تسعود وعشرين'],
  ['30','tlatin','ثلاثين'],
  ['31','wa7ed w tlatin','واحد وثلاثين'],
  ['32','jouj w tlatin','جوج وثلاثين'],
  ['33','tlata w tlatin','ثلاثة وثلاثين'],
  ['34','rb3a w tlatin','ربعة وثلاثين'],
  ['35','khmsa w tlatin','خمسة وثلاثين'],
  ['36','setta w tlatin','ستة وثلاثين'],
  ['37','seb3a w tlatin','سبعة وثلاثين'],
  ['38','tmnya w tlatin','تمانية وثلاثين'],
  ['39','tes3oud w tlatin','تسعود وثلاثين'],
  ['100','mya','مية'],
  ['101','mya w wa7ed','مية وواحد'],
  ['102','mya w jouj','مية وجوج'],
  ['103','mya w tlata','مية وثلاثة'],
  ['104','mya w rb3a','مية وربعة'],
  ['105','mya w khmsa','مية وخمسة'],
  ['106','mya w setta','مية وستة'],
  ['107','mya w seb3a','مية وسبعة'],
  ['108','mya w tmnya','مية وتمانية'],
  ['109','mya w tes3oud','مية وتسعود'],
  ['110','mya w 3chra','مية وعشرة'],
  ['1000','elf','ألف'],
  ['1001','elf w wa7ed','ألف وواحد'],
  ['1002','elf w jouj','ألف وجوج'],
  ['1003','elf w tlata','ألف وثلاثة'],
  ['1004','elf w rb3a','ألف وربعة'],
  ['1005','elf w khmsa','ألف وخمسة'],
  ['1006','elf w setta','ألف وستة'],
  ['1007','elf w seb3a','ألف وسبعة'],
  ['1008','elf w tmnya','ألف وتمانية'],
  ['1009','elf w tes3oud','ألف وتسعود'],
  ['1010','elf w 3chra','ألف وعشرة'],
  ['1100','elf w mya','ألف ومية'],
  ['1101','elf w mya w wa7ed','ألف ومية وواحد'],
  ['1102','elf w mya w jouj','ألف ومية وجوج'],
  ['1103','elf w mya w tlata','ألف ومية وثلاثة'],
  ['1104','elf w mya w rb3a','ألف ومية وربعة'],
  ['1105','elf w mya w khmsa','ألف ومية وخمسة'],
  ['1106','elf w mya w setta','ألف ومية وستة'],
  ['1107','elf w mya w seb3a','ألف ومية وسبعة'],
  ['1108','elf w mya w tmnya','ألف ومية وتمانية'],
  ['1109','elf w mya w tes3oud','ألف ومية وتسعود'],
  ['1110','elf w mya w 3chra','ألف ومية وعشرة'],
  ['10 000','3chra d l-alaf','عشرة د الآلاف'],
  ['100 000','mya elf','مية ألف'],
  ['1 000 000','mlyoun','مليون'],
  ['1 000 000 000','mlyar','مليار'],
];

NUMBER_DATA.forEach(([fr,darija,arabic])=>DATA.push({fr,darija,arabic,cat:'Nombres',note:'nombre',ex:`${fr} = ${darija}`}));
if (typeof renderCats === 'function') renderCats();
if (typeof renderCards === 'function') renderCards();
if (typeof renderFavs === 'function') renderFavs();
